apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: chaos
  labels:    
    kube-monkey/enabled: enabled
    kube-monkey/identifier: nginx-deployment
    kube-monkey/mtbf: '2'
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: '1'
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-app
        kube-monkey/enabled: enabled
        kube-monkey/identifier: nginx-deployment
        kube-monkey/mtbf: '2'
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: '1'
    spec:
      containers:
      - name: nginx
        image: nginx:1.8
        ports:
        - containerPort: 80